### ISSUE TITLE
Support tuples in .ini files

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoConf#4]
I have a config as follows:

```
[figure]
figsize=(7, 7)
```

I convert it from a string to tuple as follows:

```
      if isinstance(self.kwargs["figsize"], str):
          self.kwargs["figsize"] = tuple(
              map(int, self.kwargs["figsize"][1:-1].split(","))
          )
```

Lets build this into autconf.

**Comment by rhayes777** [comment]
If we supported YAML it would be better, as you can express types, lists and dictionaries in a sane way

**Comment by Jammy2211** [comment]
What did you get for Christmas Rich? Oh another 5 day configs refactor? Nice!
